BE/UYouBooDan/build.gradle, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/advice/ErrorResponder.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/advice/ExceptionAdvice.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/dto/BusinessLogicException.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/dto/ErrorResponse.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
어떤 종류의 PR인가요?
Issue Number: Feat#2
- Exception Advice가 추가되었습니다.
=> [BE] ExceptionAdvice Setting

BE/UYouBooDan/build.gradle, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/auditing/Auditable.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/auditing/BaseTimeEntity.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/dto/MultiResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/dto/PageInfo.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/dto/SingleResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/p6spy/P6spySqlFormatConfig.java, BE/UYouBooDan/src/main/resources/application.yml
어떤 종류의 PR인가요?
Issue Number: N/A
- Global setting 추가
=> [BE] Feat#7

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicLike.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVote.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
어떤 종류의 PR인가요?
Issue Number: #17 
- Topic Entity 클래스 생성
- TopicLike Entity 클래스 생성
- TopicVote Entity 클래스 생성
- TopicVoteItem 클래스 생성
- 완성된 클래스가 아닌 기본적인 클래스와 필드만 구현했습니다.
- 연관관계, category, status 등 은  회의 후 자세하게 결정이 되면 기능 구현하면서 진행하겠습니다.
=> [BE] Topic 기본 도메인 모델 구현 #17

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPatchReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/CommentLike.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/CommentStatus.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
어떤 종류의 PR인가요?
Issue Number: feat#19
- CommentEntity
- CommentResDto
- CommentPostReqDto
- CommentPatchReqDto
- CommentResDto
- CommentRepository
- CommentService
- CommentStatus
- CommentLike Entity
- CommentController
=> [BE] Comment 기본 도메인 모델 구현

FE/package-lock.json, FE/src/components/Main/HotVote.tsx, FE/src/components/Main/style.ts, FE/src/pages/main/index.tsx, FE/src/pages/main/style.ts
어떤 종류의 PR인가요?
Issue Number: #12 
- 핫한 투표, 마감임박페이지 레이아웃 완성
- 투표작성페이지 이후 redux, mock 연결 예정
=> [FE] 메인페이지 레이아웃 완성

FE/src/apis/overLap.ts, FE/src/apis/signUp.ts, FE/src/components/SignUp/index.tsx, FE/src/components/SignUp/style.ts, FE/src/components/layout/Header/index.tsx, FE/src/constants/regex.ts, FE/src/mocks/data/users.ts, FE/src/mocks/handlers.ts, FE/src/mocks/index.ts
회원가입페이지 기능,UI 구현 PR
Issue Number: #6 
- 회원가입 등록, UI 수정 추가 구현, form 데이터 유효성 완료, MSW 중복체크, 회원가입등록 코드 추가, Login페이지로 라우팅 설정
-
=> [FE] 회원가입페이지 95%완료

BE/UYouBooDan/build.gradle, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoOauthController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoProfile.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoToken.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/webConfig.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/util/JwtExtractUtil.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
어떤 종류의 PR인가요?
Issue Number: feat#41
- webConfig
- kakaoLogin
- webConfig는 추후 cors 이슈에 따라 내용이 변동될 수 있습니다.
- kakao로그인을 위한 밸류 클래스와 Controller 입니다.
- kakao로그인 중 자체 서버 회원 생성 및 검증을 위한 MemberService내 메소드를 구현했습니다.
- kakao정책상 유저의 email 수집 미동의 시, email은 카카오식별자+@uyouboodan.com으로 임의 가입됩니다.
- 회원 닉네임은 카카오 식별자로 대체됩니다.
- 회원 비밀번호는 yml 내 지정 비밀번호를 passwordEncording하여 임시 비밀번호로 발급됩니다.
=> [BE] CORS handling을 위한 webConfig 클래스, 카카오 로그인 구현

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicVoteItemRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #29 
- TopicPostResDTO 클래스 추가
- TopicPostResDTO 클래스 추가 
- TopicController 클래스 추가
- TopicController 클래스 내 postTopic 핸들러 메서드 추가
- TopicService 클래스 추가
- TopicService 클래스 내 createTopic 메서드 추가 
- TopicRepository 인터페이스 추가
- TopicVoteItemRepository 인터페이스 추가
- TopicEntity 클래스 기능에 맞게  일부 수정 및 연관관계 추가 
- 연관관계 매핑으로 인해 Member쪽 기능이 들어가야 확실하게 정상적으로 작동할 수 있을지 확인 가능합니다.
- PR후 Member클래스 및 Security 함께 확인후 수정한 다음 기능 정상 작동하는지 확인하겠습니다.
- 예외처리나 트랜잭션은 기능 완료 후 구현하겠습니다.
=> [BE] 투표 게시글 작성하기 기능 일부 구현 #29

FE/src/mocks/data/index.ts, FE/src/pages/_document.tsx
어떤 종류의 PR인가요?
Issue Number: #47 
- 없음
- 에러가 발생하는 부분을 삭제하였습니다
=> [FE] Mock data 에러수정

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
어떤 종류의 PR인가요?
Issue Number: #29 
- TopicVoteItem 클래스 내 필드 변수 연관관계, 생성자 추가 
- Topic 클래스 내 일부 주석 추가, 투표 게시글 상태 관리, 카테고리 관리 추가 
- TopicController 클래스 내 postTopic 핸들러 메서드 내부에서 요청의 토큰으로부터 Member 클래스 가져오는 메서드 추가하여 Topic에 추가 
- TopicPostReqDto 클래스에서 Topic 클래스로 변환하는 toTopic메서드내 투표마감일 변수 String으로 추가하도록 수정
- 예외 검증 로직은 필요한 API들 완성 후 진행하겠습니다.
=> [BE] 투표 게시글 작성하기 기능 구현 #29 

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #59 
- TopicController 클래스 내 상세 조회 getTopic 핸들러메서드 구현
- Topic Entity 클래스 내 상세 조회 관련 필드 추가
- TopicService 클래스 내 상세 조회 findTopic 메서드 구현
- TopicService 클래스 내 유효한 투표 게시글 찾는 findVerifiedTopic 메서드 구현
- TopicVoteItem 엔티티 클래스에 투표 수, 투표 여부 필드 추가
- 투표 게시글 상세 조회에 대한 Response DTO TopicResDto 클래스 구현
-  ExceptionCode 클래스에 게시글이 존재하지 않을 때에 대한 예외 코드 추가
- 투표 게시글 작성자 확인, 투표 여부, 좋아요, 조회수 의 경우 구현하는데 시간이 좀더 걸릴 것 같아서 일부 중요한 API부터 추가로 구현하고 진행하겠습니다.
- 유효성 검증, 예외처리 또한 API 완성 후 진행하겠습니다.
=> [BE] 투표 게시글 상세 조회하기 기능 일부 구현 #59

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPageResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #61 
- 투표 게시글 전체 목록 조회시 Response DTO 클래스 TopicPageResDto 클래스 구현
- TopicPageResDto, TopicResDto 클래스 내 createdAt에 시, 분, 초도 추가
- TopicController 클래스 내 getTopics 핸들러 메서드 구현
- TopicController 클래스 내 getTopic 핸들러메서드에 GetMapping 어노테이션 추가
- 투표 게시글 전체 목록 작성일 내림차순으로 정렬해서 조회하는 TopicService 클래스 내 findTopics 메서드 구현
- 투표 게시글 전체 목록 작성일 내림차순으로 정렬해서 조회하는 TopicRepository 인터페이스 내findAllByOrderByCreatedAtDesc 메서드 추가
- TopicVoteItem 클래스 내 외래키 topic id 컬럼 이름 변경
- 투표게시글 전체 목록 조회시 페이지네이션 적용했습니다.
=> [BE]  투표 게시글 전체 목록 조회 기능 구현 #61

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentMultiResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
어떤 종류의 PR인가요?
Issue Number: #67
- 댓글 좋아요 칼럼이 추가되었습니다. 
- 댓글 리스트 조회시 좋아요수가 가장 많은 댓글을 "best"로 감싸서 응답으로 보냅니다.
=> [BE] 댓글 좋아요 수 필드 추가, 베스트 댓글 조회 기능 구현

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/controller/MemberInfoController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java, BE/UYouBooDan/src/main/resources/static/db/data.sql
어떤 종류의 PR인가요?
Issue Number: feat#64
- MemberInfo 도메인 구현
- RefreshToken 기존 헤더 -> 쿠키 방식으로 변경 (보안 취약성 보완)
- Topic더미데이터 추가
- TopicRepository에 쿼리 메소드가 추가되었습니다. 다음 Topic PR 시 컨플릭트 우려가 있습니다.
- ExceptionCode 부분 오타를 수정했습니다. 컨플릭트가 발생할 시 확인 해보시면 좋습니다.
=> [BE] MemberInfo 도메인 구현, RefreshToken 쿠키 방식으로 변경, Topic더미데이터 추가

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
어떤 종류의 PR인가요?
Issue Number: #80 
- 마이페이지 내 댓글 조회 기능이 추가되었습니다.
- 삭제된 댓글을 수정, 삭제, 좋아요 시 "이미 삭제된 댓글입니다."라는 에러를 응답합니다.
- 작성자 외 사람이 댓글을 수정 및 삭제 시 "권한이 없습니다."라는 에러를 응답합니다.
=> [BE] 마이페이지 내 댓글 조회 구현, 댓글 예외처리 구현

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java, BE/UYouBooDan/src/main/resources/static/db/data.sql
어떤 종류의 PR인가요?
Issue Number: #91 
- Comment와 Member의 다대일 연관관계를 매핑하였습니다.
- Comment와 Topic의 다대일 연관관계를 매핑하였습니다.
- Comment의 Mock data의 칼럼명 수정이 있습니다.
- findMemberComment의 파라미터 순서를 변경하였습니다.
=> [BE] comment 연관관계 매핑

BE/UYouBooDan/src/main/resources/static/db/data.sql
어떤 종류의 PR인가요?
Issue Number: #93 
- data.sql Member_roles로 테이블명을 변경하였습니다.
=> [BE] data.sql Member_roles 변경

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
어떤 종류의 PR인가요?
Issue Number: #103 
- TopicController 클래스 핸들러메서드 getTopic에서 로그인 여부 확인하는 메서드 호출 사용
- 투표 게시글을 상세 조회할 때  로그인한 사용자인지 아닌지 확인하여 투표를 했는지, 작성자인지 여부에 대한 응답 추가하였습니다.
=> [BE] 투표 게시글 상세 조회시 조회하는 사용자의 로그인 여부에 따른 응답 수정 #103

BE/UYouBooDan/appspec.yml, BE/UYouBooDan/build.gradle, BE/UYouBooDan/buildspec.yml, BE/UYouBooDan/scripts/deploy.sh, BE/UYouBooDan/scripts/initialize.sh, BE/UYouBooDan/scripts/server_clear.sh, BE/UYouBooDan/scripts/server_start.sh, BE/UYouBooDan/scripts/server_stop.sh, BE/UYouBooDan/src/main/resources/application-real.yml, BE/UYouBooDan/src/main/resources/application.yml, BE/UYouBooDan/src/main/resources/bootstrap.yml
어떤 종류의 PR인가요?
Issue Number: #100 
- Github Actions 위한 초기 설정 파일을 생성하였습니다.
- application-real.yml을 새롭게 생성하였습니다.
- application.yml 에서 spring active: real로 되어있습니다. 로컬에서 작업하시던 분은 local로 바꿔서 작업해주시면 감사하겠습니다.
=> [Deploy] Github Actions 위한 초기 설정 파일

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicLikeResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicLike.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicLikeRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #104 
- Topic Entity 클래스에 게시글 좋아요 리스트와 좋아요 개수세는 메서드, 조회하는 사람이 좋아요했었는지 여부 확인하는 메서드 추가
- TopicController 클래스에 게시글에 좋아요 하는 메서드 추가
- TopicService 클래스에 게시글에 좋아요하는 메서드, 좋아요 개수 세는 메서드, 게시글 조회시 좋아요 되어있는지 메서드 추가 
- TopicLikeRepository 인터페이스 생성하고 게시글 좋아요했는지 여부 확인하는 쿼리 메서드 추가 
- TopicLike 클래스에 생성자, 좋아요 하고 취소하는 상태 전환 메서드 추가, NoArgsConstructor 어노테이션 추가, id에 생성전략 어노테이션 추가, 투표 게시글에 대한 연관관계 매핑, 사용자에 대한 연관관계 매핑 추가 
- TopicResDto 클래스에 좋아요수와 좋아요했는지 여부확인하는 로직 추가
- 좋아요 이후 응답에 대한 TopicLikeResDTO 클래스 추가
- 로그인한 사용자만 투표 게시글에 추천할 수 있고 투표 게시글 조회시 투표 게시글에 추천했는지 여부와 추천수 함께 응답을 전송합니다.
=> [BE] 투표 게시글 추천하기 기능 구현 #104

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #110 
- TopicService 클래스 내 findTopics 메서드내 핫 토픽 조회 case에 진행중인 투표 게시글로 반환하는 로직 추가 
- 핫 토픽 조회 기능 구현간 엔티티나 서비스, 레포지토리 변경하는데 있어 많은 부분을 바꾸게 되고 그 과정에서 버그가 발견되었습니다. 버그를 고치게 되면서 많은 로직은 건드리게 되어 더 문제가 발생할 가능성이 높습니다. 
- 일단은 프론트쪽에서 API를 이용하여 응답을 받는것이 더 중요하다고 생각하여 해당 API로 응답을 받을 수 있게만 일단 임시로 대체하여 구현했습니다. 이후 추가적인 정리, 의논 후 다시 구현 진행하겠습니다.
=> [BE] 전체 게시글 중 핫토픽 조회 기능에 진행 중인 투표 게시글 조회로 대체하여 구현  #110

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentLikeResDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
어떤 종류의 PR인가요?
Issue Number: #113 
- 댓글 좋아요시 응답으로 총 좋아요 수가 포함되도록 업데이트하였습니다.
=> [BE] 댓글 좋아요 시 해당 댓글 총좋아요수를 포함하여 응답

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #115 
- TopicController 클래스 내 
- getTopics 메서드의 parameter에 category 추가
-  topicService메서드 호출시 category 를 arument로 넘기는 부분 추가
- 주석 변경
- TopicService 클래스내
- findTopics메서드 parameter에 category 추가 
- 주석 변경 
- 프론트쪽에서 api로 응답을 받을 수 있게 구현을 했습니다.
- 기능 구현만을 생각해서 구현할수는 있으나 쿼리 메서드와 서비스 클래스 코드가 길어지고 로직이 복잡해져 유지보수 혹은 가독성이 떨어질 것 같아서 관련된 내용 추가적으로 학습하고 구현하도록 하겠습니다.
=> [BE] 카테고리별로 투표 게시글 조회하는 기능 API 응답 구현 #115

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
어떤 종류의 PR인가요?
Issue Number: #110 
- Topic Repository 인터페이스내 핫토픽 조회하는 findAllByHot 쿼리 메서드 추가
- Topic Service 클래스 findTopics 메서드 내 핫 토픽 조회하는 로직 추가 
- 전체 투표 게시글 목록 조회시 filter 쿼리 파리미터에 hot으로 값을 지정시 핫토픽 게시글 목록 조회하여 보여줍니다.
- 조회 관련해서 레포지토리의 쿼리 메서드가 늘어나고 있습니다. 추가적인 학습 후 리팩토링 하겠습니다.
=> [BE] 전체 진행중인 투표 게시글 중 핫 토픽 조회 기능 API 구현 #110

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
어떤 종류의 PR인가요?
Issue Number: #138 
- Topic 클래스의 Category Enum 클래스 안에 일반, 패션뷰티, 쇼핑, 반려동물, 취미운동 카테고리 추가
- 일반,음식,  패션뷰티, 쇼핑, 반려동물, 취미운동 6가지 카테고리만 사용할 수 있도록 카테고리를 추가하였습니다.
=> [BE] 투표 게시글의 카테고리 추가 #138

BE/UYouBooDan/build.gradle, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicVoteReqDto.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/util/validator/ValidDate.java, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/util/validator/ValidDateValidator.java
어떤 종류의 PR인가요?
Issue Number: #145 
- TopicController 클래스에 유효성 검증 추가 
- @Validated 어노테이션 추가
- postTopic메서드 ReqDto 클래스 매개변수에 @Valid 어노테이션 추가
- getTopic, patchTopicVote, postTopicLike, patchTopic, deleteTopic 메서드 매개변수 topicId에 @min(1)어노테이션 추가
-
- TopicPostReqDto 클래스에 유효성 검증 추가 
- category, title, closedAt 필드에 @notblank 추가
- closedAt 필드에 날짜형식 유효성 검증위한 커스텀 어노테이션 @ValidDate 추가
- 투표항목 리스트 topicVoteItems 필드에 @Valid, https://github.com/NotNull, @SiZe(min = 1) 추가
- 투표항목이름 topicVoteItemName에 @notblank 추가
- TopicVoteReqDto 클래스에 유효성 검증 추가
- 투표 항목 id에 @notblank, @min(1) 추가
- 날짜 형식 유효성 검증 위한 커스텀 어노테이션 ValidDate 추가
- 날짜 형식 유효성 검증 위한 ValidDate 커스텀 어노테이션의 Validator 클래스 ValidDateValidator생성
- build.gradle 파일에 db효성 검증 위한 validation 라이브러리 추가
-
=> [BE] 투표 게시글 작성, 조회, 투표시 요청에 대한 유효성 검증 추가 # 145

BE/UYouBooDan/gradlew, BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
어떤 종류의 PR인가요?
Issue Number: #100 
- gradlew 파일 생성
- commentRepository 수정
=> [BE] gradlw 파일 생성, commentRepository 수정

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
어떤 종류의 PR인가요?
Issue Number: 
- be 브랜치를 dev 브랜치로 병합합니다.
=> [BE] be 브랜치를 dev 브랜치로 merge

BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicVoteReqDto.java
어떤 종류의 PR인가요?
Issue Number: #159 
- TopicVoteReqDto클래스 내 투표 항목 아이디 topicVoteItemId 필드에 유효성 검증 NotNull로 수정
=> [FIX] fix: 투표 요청시 400 Bad Request 응답에 대한 버그 픽스  #159
